[build]
  command = "npm run build && echo '<!DOCTYPE html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>TempFile.Link</title><link rel=\"icon\" type=\"image/x-icon\" href=\"/favicon.ico\"></head><body><div id=\"__nuxt\"></div><script type=\"module\" src=\"/_nuxt/entry.CUmDD1ED.js\"></script><link rel=\"stylesheet\" href=\"/_nuxt/entry.CUmDD1ED.css\"></body></html>' > .output/public/index.html"
  publish = ".output/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"